language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
install:
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=tpDcc
- sphinx-apidoc -f -e -o docs/sphinx tpDcc
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: Me8OOOCTe0ElMqnE1PRQWGHOqcXu5bHPdz1fCKrrDAZNp3thytRmlmtITcvyk/RHzWj6h5CbxMhqbsarzlMGkahMZ3s+e2uKwhRYI501ilOENWeVMgrqmj2pEw9Z3ZTFkCZilD/Gu0EHppIH4ISTAUaNRciae/W9LLgdrJKYZdXfNl7g9/MGYRH9mtFVuVig1PVYsaSTJndoe25Rv475K9Df94zvmb8tCcEacjWCZnWiwSyPMwH/8otfqsFj7vOhiW2cUq3Y3InYF41MD8Jg//XtkHQElJIS3Vr8FYnKlxuLvx2ae/3QpKdvM4TGaqMbiSlbQbjjDvdEH2hnbAR+1Cthzhcfk099YqvtSkUh5RryILh41mEOg0IqsT//nmM4PDZqTfPVtbkVJNtlVpLBrFCmydlepGotCf2SIK+EWf1zfIiNXmxsKTK1bcT6YbdohcQCvTkvEt/2X2qm4aDwWAU1v6JJpwGrXNkeIYMs1U17bCWxO5ZLgzZH0Xlyqg6zHC4BOvsedJE/6RhpYXEchT/+ZV/Hesobe6hWhIBO+Da+JQLmz0vE+MNHapa6noXxSf7UxUie+TcksRsHGztNy+2rewtRJ52dE1SAuWJP8KIGARp1P8eb9YONBTvDjL7fT6qfGc8agWiIWFa1h7L3SVFkJZo+KFcU/GLBRE1UgHI=
    on:
      branch: master
      tags: true