language: python
python: 2.7
script:
- pytest
deploy:
  provider: pypi
  user: tpoveda
  password:
    secure: onf91l99CyhMNuBXTJqLGTsaw5cYnfpT5Wg5hXWjKEZcDn4rDdT5PlC9r3jNah3aGDHxQm3baC+UOLBEUcbQ3lSM/8TAdk72WGNhd1nqba8GT0Z6qDEIWzP+phW486kOxrbIOLJsreSTsPeKejthLld1DMw/RnMAdXrQ6WxW7FtQfka6blr/sUx6ITsb6yrxf68iOl8NFlAOK0tqOZsD3lo/UBw3RDE8FS3HbYitxSeEZ/LPtMCZGE6nyg5d4M+J+uTXoWkGOHa5MNnAZ2It5RvmaxxkxGE9PQzpv9pGpoepkufYp1NHXrBSq5VOhgw2oFlE0jL2f7y4uSNe0pZuzgOUdSyPo24Zev78g/YQqmY77wca/ILTsSZpI6UyuRf/YzVBPwdt47qr+u4YRj664nRryDPJcMaI3OSI1uRjzi0qELuChnWeRxbs/f7NSgfFnF8EemBn5XuJtTNPeqEGaBCJZUOO7J2oXA7/nWPpO8Ial7gn2CBG+ch7c647BAeAGJqeqGrFkN1FaNct6eOrvW0/9zGgha7f4lrgACGJOvhXVyonOJr1p36roeAZ31w/Mnhu9BJ2DFHBcszD2JksxvHbC7MiLDMRm3LQCINapgXVE5IxjmiVUKJgyT2Xie/q9sscIvL/mbdkB7NWhgn0QkhI8dZA7RkRBzg73M2r5NY=
  skip_cleanup: true
  on:
    tags: true
