language: python
install:
  - "python setup.py install"
script:
  - pytest
deploy:
  skip_cleanup: true
  provider: pypi
  user: tpoveda
  password:
    secure: ZUSoRcbo/7DyuCgXRQekri/zb/8UCxeULvEA2SjqOs4ZQ4qDA+J+EkgGi7eSYtd3vieQpBl88ndQooJW5ThQ4mJ0ZQyskLxI2QRKWA3P/FT7mpwHg2tJF7Hb+tjYohndOC4M+aDeyi/r16rsAFqBMCgyvNMknXYXB21XtNACVRK6Eh59x1SVEalTCxqJNJaA3uHeJHQDDRuvL0DHzfLC56j+07V00caPG2ZJwWoF1Xeo7q6w5vXubB8pkK8/Q9SjA7824MWKN3Dzo+Z3BrbPxYkeEMyHZa8cwRypPkpZGIXhdfc8vk9FAXlELfe0eYATub60Pat9TcgLczn464GSFHZPXAaFlcWYQbOx34BpfIr8PlLsoQDy/AUPwSeMLZSy5eNtvJ7SVQ2I6zrD3tDHG9Uli6W2ZTVaSQlPAn88f6QMtnDUKZ0uhz8SRhuNkWcyoR0wYmGWlHB64m97QJKcxC7I2PYP5pIHWG8r+8Gv6ygNtiWda7jBpaK9wzYNcOwcV86PKcK5RsZaNtkX5j5xTyM7zv/wOoWNzR0x+uO2AjO1dc34gpdUkPcSjCtFsIIgXiPa0sGVkkQXT/+DKoLqUdoGigDT7/2bZNuCi9LQe6sxSPOYp+qY33cHEgmVQvB/nO3dLnK5y7QOWtPfABVQDX3LA5mw+5v3aDtVxdCanDA=
  on:
    branch: master
    tags: true
