language: python
python: 2.7
script:
- pytest
deploy:
  provider: pypi
  user: tpoveda
  password:
    secure: "kZwnicD57zVa080VKaEJCXv5StY+AqFwCyTQJR4pvRS3K7tdUMIAM3VR+GHyQ+nyuEWGSLdXUYZVtkd0g1GlI+Ijif86e4Wym8T93QjtbPygrU+LfCnbIKJcVdGd6MmljXLFKgp7tVdca2LwA0zyTIon7dozAy+thHVUZw0/ZHnJurWHYI8b2IvCUqDsnjD+Lr3Tf6eVOjzAFX1kdSIh+DNtmeUcRgFPvRcs7JkgEBQVNvPFes1Uq83OJcp04uPnQO9D+vOhAsbW5KpDbXIecSGupDWU0jgQEmIA1ehEEN0JWYUo4BHQo6w8S7pnjZqHMwBNLmYSLyibxeDsLj5DZUdzKisCeUa1K1B/UJ+HPDt89oHstMnkVmYOBOa+PGgRGJ4+YdRtExyUQWxqneMwrcNsOMtoH4xt0S8/8xD4SbssBIJbp79hqgE6AhxnC285j7x8WIdOvbTHjqwkPMC1y5aOih0CDFU8+RGiUQ/J2aDY4E9KSR0LuX9+27Cb4OhmCmGUFUUhAOXLMgxbhWwN9bbA/5iQxQg3MYYlh4MjFPogsVbEk2tZYd8Lht3E8o2ZRj3/ZoxZi6Bc/3iJ3TsiVt4MnIG5pd+yc7CRFWPsXJg1A5RNpdoYPG4sahM8y3x7Zvr0Ynx61MHDILZAnjR8syfGYTqRBMhI+qXx6cBzNJU="
  skip_cleanup: true
  on:
    tags: true
